version: 0.0
os: linux
files:
  - source: .next
    destination: /home/ubuntu/video-animations/.next

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/sync_s3.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/restart_application.sh
      timeout: 60
      runas: ec2-user
