version: 0.0
os: linux
files:
  - source: .next
    destination: /home/ubuntu/VA/.next

hooks:
  BeforeInstall:
    - location: /home/ubuntu/VA/scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: /home/ubuntu/VA/scripts/application_stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: /home/ubuntu/VA/scripts/sync_s3.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: /home/ubuntu/VA/scripts/restart_application.sh
      timeout: 60
      runas: ec2-user
