version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/VA/
hooks:
  BeforeInstall:
    - location: scripts/stop-application.sh
      timeout: 300
  AfterInstall:
    - location: scripts/git-pull.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/install-and-build.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/start-application.sh
      timeout: 300
