version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ubuntu/VA/
hooks:
  BeforeInstall:
    - location: /home/ubuntu/VA/git-pull.sh
      timeout: 300
  AfterInstall:
    - location: /home/ubuntu/VA/build.sh
      timeout: 300
