version: 0.0
os: linux
files:
  - source: .next
    destination: /home/ubuntu/VA/

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/sync_s3.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/restart_application.sh
      timeout: 60
      runas: ubuntu
