version: 0.0
os: linux

phases:
  install:
    commands:
      - echo "Starting install phase..."
      - pm2 stop 1
      - npm install
      - git pull
      - npm install
  build:
    commands:
      - echo "Starting build phase..."
      - npm run build
      - pm2 start 1
 
artifacts:
  files:
    - '**/*'
  base-directory: .next

cache:
  paths:
    - node_modules/**/*
