const nodemailer = require("nodemailer");
export default async function POST(req, res) {
  try {
    const { name, email, phone, message, IP, pageUrl } = await req.body;
    const transporter = nodemailer.createTransport({
      service: "Gmail",
      host: "smtp.gmail.com",
      port: 587,
      secure: 'starttls',
      auth: {
        user: "developer@infinitimediainc.com",
        pass: "mfbahadsoeevtdsd",
      },
    });
    const mailOptions = {
      from: "developer@infinitimediainc.com",
      to: [
        "developer@infinitimediainc.com"
      ],
      subject: `New Lead Generated By Video Animation`,
      html: `<table>
                    <tr>
                        <th>Name</th>
                        <td>${name}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>${email}</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td>${phone}</td>
                    </tr>
                    <tr>
                        <th>Message</th>
                        <td>${message}</td>
                    </tr>
                    <tr>
                        <th>IP</th>
                        <td>${IP}</td>
                    </tr>
                    <tr>
                        <th>pageUrl</th>
                        <td>${pageUrl}</td>
                    </tr>
            </table>`,
    };
    await transporter.sendMail(mailOptions);
    return res.json({ message: "Email send sucessfully", status: 200 });
  } catch (error) {
    return res.json({
      message: "Failed to send Email",
      data: error,
      status: 500,
    });
  }
}
